variables:
  MAVEN_CACHE: '$(Pipeline.Workspace)/.m2/repository'
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE)'
  PLANTUML_VERSION: '1.2022.6'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false