# tomcat
server:
  port: 8001
spring:
  application:
    name: backupDB
  boot:
    admin:
      client:
        url: "http://localhost:8104"
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: ${spring.application.name}	# 注册到consul的服务名称
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# backup datasource
benjamen:
  backup:
    datasource:
      host: 175.178.51.92
      userName: root
      password: 123456
      database: db41026
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8102/eureka/
#    instance:
#      hostname: localhost