server:
  port: 7000
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone:
        http://localhost:${server.port}/eureka/
  instance: localhost